### PR TITLE
Added tests for some common set theory identities

### PR DESCRIPTION
**Pull request by KarlLundengaard**

### CODE REVIEW

**Comment by aplr** [comment]
Ok thanks, I'll have a look into it. De Morgan is weird and should work already, I guess for the union with the complement we need to set up SymPy another way. Let's see what I can do before handing the written thesis in, otherwise this would be future work, improving the evaluation algo.

**Comment by KarlLundengaard** [comment]
> Ok thanks, I'll have a look into it. De Morgan is weird and should work already, I guess for the union with the complement we need to set up SymPy another way. Let's see what I can do before handing the written thesis in, otherwise this would be future work, improving the evaluation algo.

Looking at the sympy documentation I would start with changing the transformer to output boolean algebra expressions instead of sets directly (they seems to be better intended for this kind of application), i.e. the ast transformer does the opposite of the as_set function described here: https://docs.sympy.org/latest/modules/logic.html#sympy.logic.boolalg.Boolean.as_set

**Comment by aplr** [comment]
Thanks, I'll try that!

**Comment by aplr** [comment]
Addressed in #2 

Thanks @KarlLundengaard for raising this

**Pull request closed without merging**
